// GENERATED FILE — do not hand-edit (Doc 17 rule 8).
// Regenerated by `npm run db:types` after every migration change, against
// the local Supabase Postgres instance. Empty until Phase 2's first
// migrations land; @abhyas/platform's db adapter will import `Database`
// from here once it exists.
export type Database = Record<string, never>;
