-- Abhyas V2 — drop coach_profiles.sport_keys (dead column).
--
-- Added in 0016_coach_profiles.sql as "one sport taxonomy, not two" (reusing
-- taxonomy_sports/listings.sport_keys, migration 0013) since the categories/
-- subcategories/tags taxonomy (migration 0019) didn't exist yet. Once it
-- did, CoachProfileWizard switched Category/Specialties over to it but kept
-- sport_keys as a hidden, unedited pass-through "so Explore/Marketplace
-- search doesn't regress" (0019's own header, point re: sport_keys).
--
-- That search surface is gone: /explore's public coach search now filters
-- coach_profiles by category_id/subcategory_ids/tag_ids/age_groups/
-- skill_levels only (GET /api/v1/public/coaches, migration 0020) — nothing
-- reads coach_profiles.sport_keys anymore, only the wizard's hidden
-- pass-through still wrote to it. Column, index-free (no index existed on
-- this column), safe to drop outright.
--
-- NOTE: this is unrelated to listings.sport_keys / taxonomy_sports
-- (migration 0013), which stay — the org-listings feature (/marketplace
-- console, /explore/[slug], leads/reviews) still actively uses those.

alter table coach_profiles drop column sport_keys;
